const $ = s => document.querySelector(s); let sourceFolder = '', targetFolder = '', mods = [], timer, picking = false;
async function api(url, data, signal) { const r = await fetch(url, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(data || {}), signal }); const d = await r.json(); if (!r.ok) throw Error(d.error); return d; }
function setPath(kind, value) { (kind === 'source' ? $('#sourcePath') : $('#targetPath')).value = value || ''; }
async function applyPath(kind, value) { const folder = value.trim(); if (kind === 'source') { sourceFolder = folder; if (folder) await scan(); } else { targetFolder = folder; } updateAction(); }
async function pick(kind, button) { if (picking) return; picking = true; const buttons=[...document.querySelectorAll('[data-choose]')], original = button.textContent, controller = new AbortController(); buttons.forEach(b=>b.disabled=true); button.textContent = '正在打开…'; const timeout=setTimeout(()=>controller.abort(),30000); try { const {folder} = await api('/api/choose-folder', {}, controller.signal); if (!folder) { alert('没有选择文件夹。你也可以直接在输入框粘贴 mods 文件夹的完整路径。'); return; } setPath(kind, folder); await applyPath(kind, folder); } catch (e) { const reason=e.name==='AbortError'?'文件夹选择器等待 30 秒后仍未返回。':'无法打开文件夹选择器：'+e.message; alert(`${reason}\n\n请直接在输入框粘贴 mods 文件夹的完整路径。`); } finally { clearTimeout(timeout); buttons.forEach(b=>b.disabled=false); button.textContent=original; picking=false; } }
async function scan() { $('#list').innerHTML='<div class="empty">正在读取 JAR 元数据…</div>'; try { mods = (await api('/api/scan', {folder:sourceFolder})).mods; render(); } catch(e) { $('#list').innerHTML=`<div class="empty">读取失败：${e.message}</div>`; } }
function render() { $('#count').textContent = mods.filter(m=>!m.locked).length; const list = $('#list'); list.innerHTML = ''; if (!mods.length) { list.innerHTML='<div class="empty">该文件夹没有可读取的 .jar 模组。</div>'; return; } for (const mod of mods) { const node = $('#modRow').content.firstElementChild.cloneNode(true); const input=node.querySelector('input'); input.checked=!mod.locked; input.disabled=mod.locked; input.dataset.id=mod.id; node.querySelector('strong').textContent=mod.name; node.querySelector('small').textContent=`${mod.id || '未识别 ID'}  ·  ${mod.version || '未知版本'}  ·  ${mod.file}`; node.querySelector('.tag').textContent=mod.loader; node.querySelector('.lock').textContent=mod.locked?'🔒':mod.unrecognized?'?':''; if (mod.unrecognized) { input.checked=false; input.disabled=true; node.title='未能识别内部元数据，无法安全自动迁移'; } list.append(node); } updateAction(); }
function updateAction() { $('#migrate').disabled = !(sourceFolder && targetFolder && $('#version').value.trim() && $('#loader').value && mods.some(m => !m.locked && !m.unrecognized && $('#list input[data-id="'+CSS.escape(m.id)+'"]')?.checked)); }
document.addEventListener('change', e => { if(e.target.matches('#list input') || e.target.matches('#loader')) updateAction(); }); document.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>pick(b.dataset.choose,b)); $('#sourcePath').addEventListener('change', e=>applyPath('source', e.target.value)); $('#targetPath').addEventListener('change', e=>applyPath('target', e.target.value)); $('#version').addEventListener('input', updateAction); document.querySelectorAll('.folder-path').forEach(input=>input.addEventListener('keydown', event=>{ if(event.key==='Enter') input.blur(); }));
$('#migrate').onclick = async () => { const excludedIds = mods.filter(m=>!m.locked&&!m.unrecognized&&!$('#list input[data-id="'+CSS.escape(m.id)+'"]')?.checked).map(m=>m.id); try { const data=await api('/api/migrate',{sourceFolder,targetFolder,gameVersion:$('#version').value.trim(),loader:$('#loader').value,mods,excludedIds,curseForgeApiKey:$('#curseKey').value}); $('#activity').classList.remove('hidden'); $('#migrate').disabled=true; $('#log').innerHTML=''; poll(data.id); } catch(e) { alert(e.message); } };
async function poll(id) { try { const job=await fetch('/api/job/'+id).then(r=>r.json()); const pct=job.total?Math.round((job.completed/job.total)*100):0; $('#percent').textContent=pct+'%'; $('#bar').style.width=pct+'%'; $('#current').textContent=job.current || (job.status==='complete'?'迁移完成':'正在准备…'); $('#log').innerHTML=job.logs.slice(-50).map(l=>`<div class="${l.type}">${l.type.toUpperCase()} · ${l.message}</div>`).join(''); if(job.status==='complete'){ if(job.logFile) $('#current').textContent='迁移完成 · 完整日志：'+job.logFile; renderResults(job); $('#migrate').disabled=false; return; } if(job.status==='error'){ $('#current').textContent='迁移失败：'+job.error; return; } timer=setTimeout(()=>poll(id),700); } catch(e) { $('#current').textContent='无法读取进度：'+e.message; } }
function renderResults(job) { const migrated=job.results.filter(x=>x.status==='migrated').length, missing=job.results.filter(x=>x.status==='skipped'||x.status==='error'); const panel=$('#activity'); const old=panel.querySelector('.results'); if(old)old.remove(); const el=document.createElement('div'); el.className='results'; const config=job.configs ? `<div class="result"><span>配置与快捷键：已迁移 ${job.configs.copied.length} 个${job.configs.backedUp.length?`，已备份 ${job.configs.backedUp.length} 个旧文件`:''}${job.configs.error?`（${job.configs.error}）`:''}</span></div>` : ''; el.innerHTML=`<div class="eyebrow">完成 · 已迁移 ${migrated} 个</div>`+config+missing.map(x=>`<div class="result"><span>${x.mod.name} — ${x.reason||'未迁移'}</span><span>${x.links?`<a target="_blank" href="${x.links.modrinth}">Modrinth</a><a target="_blank" href="${x.links.curseforge}">CurseForge</a><a target="_blank" href="${x.links.mcmod}">MCMOD</a>`:''}</span></div>`).join(''); panel.append(el); }
